### PR TITLE
[WIP] Rename a project

### PR DESCRIPTION
**Pull request by gideonthomas**

### CODE REVIEW

**Comment by gideonthomas** [comment]
@flukeout here's what it looks like so far, any comments?
rename on thimble

**Comment by flukeout** [comment]
Looks good - I'd lower the font-size a bit on the Save button match the publish button more closely. Otherwise looks solid! :+1:

**Comment by gideonthomas** [comment]
Blocked on publish.webmaker.org implementing a renaming solution for projects and on https://github.com/humphd/brackets/issues/385

**Comment by gideonthomas** [comment]
Moved here: https://github.com/mozilla/thimble.webmaker.org/pull/709

**Pull request closed without merging**
