### PR TITLE
Added green header to My Projects page

### LINKED ISSUE #806: Add header to My Projects page
Should be the same header as the landing page. 

Need UI for an authenticated state, I believe. /cc @flukeout

### PR DESCRIPTION
**Pull request by flukeout**
image

Fixes #806

### CODE REVIEW

**Comment by flukeout** [comment]
@humphd or @gideonthomas Need a bit help in this one.. 

The functionality for this page ``views/editor/projects.html`` lives in a couple of places...
* ``editor/scripts/open-project.js`` -  handles the Create New button and opening projects
* ``homepage/scripts/main.js`` -  handles simplified user dropdown (to mimic the hompeage)

The ``open-project.js`` script is included on the page like this...
```
<script src="/scripts/vendor/require.min.js" data-main="/editor/scripts/open-project.js"></script>
```

It seems that only one of the scripts can be included in this fashion as the ``src`` would point to the same require.file.

Anyway - what's a good solution? It also seems like a lot to include the all homepage scripts just for the user dropdown.

**Comment by flukeout** [comment]
Looks like this and works as long as we can find a way to include both of the scripts listed in my previous comment...

image

**Comment by flukeout** [comment]
@gideonthomas r?

**Comment by gideonthomas** [comment]
I think this looks right!

**Comment by flukeout** [comment]
Thanks @gideonthomas - merged.

**Comment by hannahkane** [comment]
I'm seeing this:

screen shot 2015-12-03 at 12 59 10 pm

**Comment by hannahkane** [comment]
can no longer reproduce. disregard.

**Pull request merged**
