### PR TITLE
Fixes  #1012 Switch to Universal Analytics tag

### LINKED ISSUE #1012: Use Universal Analytics version of GA
We're using the latest version of GA across our projects now, so need to update the tracking code here: `public/homepage/scripts/google-analytics.js`

I'll work on a PR for this now.

### PR DESCRIPTION
**Pull request by adamlofting**
Not sure who to R? 

So starting with @humphd @sedge :smile: 

This is how we're currently using GA with old Thimble.

### CODE REVIEW

**Comment by adamlofting** [comment]
Fixes #1012

**Comment by gideonthomas** [comment]
r=me with rebase

**Comment by adamlofting** [comment]
@gideonthomas can I double check what this rebase is for? I'm not seeing any conflicts but might have missed something?

**Comment by gideonthomas** [comment]
@adamlofting sorry, we usually do a fast-forward merge so we rebase to keep the history linear and manually merge into the tree! I just did it for you though :)

**Pull request closed without merging**
