### PR TITLE
Hide published details bar when on mobile phones without enough room

### PR DESCRIPTION
**Pull request by humphd**
@flukeout, see if this is good enough for now, so we don't crowd out the page content on a mobile phone.

### CODE REVIEW

**Comment by flukeout** [comment]
@humphd Looking now

**Comment by flukeout** [comment]
@humphd I don't have a good way to test this out, as I'm not able to publish locally at the moment. Were you able to run this on a device?

One comment is that we're adding a ``padding-top: 64px`` to the body element to accomodate the details bar when it's visible...

image

So, if we're going to hide the bar, we should remove that padding too.

**Comment by humphd** [comment]
@flukeout take a look at this last commit, see if this fixes it.

@gideonthomas can you test this locally please?  The goal is not to have the remix stuff show at all on a phone.

**Comment by flukeout** [comment]
@humphd seems good - can we push it to staging for testing?

**Comment by humphd** [comment]
Landed on staging, let's try this out tomorrow.

**Comment by flukeout** [comment]
:+1:

**Comment by humphd** [comment]
It's not quite right.  Here's a follow-up: https://github.com/mozilla/thimble.webmaker.org/pull/1212

**Comment by humphd** [comment]
This has all been backed out now.

**Pull request merged**
