### PR TITLE
Fix #1138, #817 - user menu should open when clicked vs hovered.

### LINKED ISSUE #1138: Website menu disapears
A very silly bug, but with FF 40.0.3 win Windows 7 and 8 but not with Chrome the menu at the top right after signing in on https://thimble.mozilla.org/ is slightly below the Hi, USERNAME hover menu item such that the menu (Your projects, New projects, sign out) disappears if you try and select it unless you are very fast or have a touch screen.

### PR DESCRIPTION
**Pull request by humphd**
This re-uses our PopupMenu code to have the usermenu work like the rest of our popup menus (esc key closes, clicking outside it closes).

### CODE REVIEW

**Comment by flukeout** [comment]
@humphd The menu on the homepage doesn't open via click (nor via hover).

**Comment by flukeout** [comment]
@humphd Tested again, now with a different error.

STR
* Load up your branch, restart server
* Go to homepage
* Menu works
* Click New Project
* Go to Editor
* Menu doesn't work
* Refresh the Page - menu works

menu

There isn't really anything in the console that seems related or helpful.

**Comment by humphd** [comment]
This is great, thanks for the details @flukeout .  I'll debug tomorrow.

**Comment by gideonthomas** [comment]
I can't reproduce @flukeout's issue

**Comment by humphd** [comment]
I can't either, so let's have @flukeout do this on vidyo so we can see it and figure out his extra steps.

**Comment by flukeout** [comment]
The ole' wait a day until it goes away strategy worked! Can no longer reproduce! R+

**Pull request merged**
