### PR TITLE
Tutorial styling updates

### LINKED ISSUE #1267: Handle overflow in Tutorial's pre.code
Thimble's Tutorial.html includes &lt;pre class="code" &gt; as a preset style. Long lines break the box. Fix with ```.code { overflow:auto; }``` or similar.

### PR DESCRIPTION
**Pull request by flukeout**
**Some fixes**
* Images need a special class ``.border`` now to display in the Polaroid style
  * This makes it so you can inline regular images
  * These images have a max width of 100% now too, so they won't cropped by the edge of the tutorial
* Changed the cat image to a small screenshot of the Thimble site
 * I was hotlinking some random image from some kind of veterinarian org, oops!
* Code that is too long for it's ``<pre class='code'>`` container now scrolls instead of continuing past the bounds

Fixes #1267 
Fixes # 1232

### CODE REVIEW

**Comment by flukeout** [comment]
@gideonthomas R?

**Comment by humphd** [comment]
This looks good.  One thing I notice is that there's a vertical alignment issue with the numbered lists:

screenshot 2015-12-02 20 24 44

That may not be new, but FYI, in case you caused it and/or want to fix it here.

r=me otherwise.

**Comment by flukeout** [comment]
Thanks @humphd Updating now.

**Comment by flukeout** [comment]
And merged!

**Pull request merged**
