### PR TITLE
Fix #828 - Server and client implementation of Tar streaming files

### LINKED ISSUE #821: Add a google verification page to bramble.mofostaging.net
So, if we want to link from a Youtube video to our site, we need to "Verify" that we own that site. It's weird, I know. To do so, we need to add this file to our codebase...

https://dl.dropboxusercontent.com/u/109902/bramble/google3479be6196d04fac.html

So that it will be available at http://bramble.mofostating.net/google3479be6196d04fac.html

@humphd Can you help?

### LINKED ISSUE #828: Implement tar streaming for transferring files from server->client
Right now when we send the project files to the client, we send one large JSON object containing all the file buffers which are JSON parsed. This is how it is being received from publish.webmaker.org.
Instead we are teaching publish.wm.org to stream tarballs when requesting a collection of files (all files for a project). We should stream this down to the client as well.

On the client-side, this will also involve some other things besides teaching it to read a tar stream and untar:
* The server will no longer provide the project root in the "makedetails". Instead, the project id will be rendered into the makedetails object. From this, the client needs to figure out the project root! For authenticated users, it will be `/userId/projects/projectId`. In the makedetails, the projectId will be rendered as `id` and the userId will be rendered as `userID`. For an anonymous user, the path will be `/projectTitle` (which will change in https://github.com/mozilla/thimble.webmaker.org/pull/815 later).
* A consequence of the above is that when the client sends a path to the server, it **must** send a path sans the project root. For e.g. to request the server to update `/1/projects/5/index.html`, the client will send the path `/index.html`.

There probably will be a few more changes that a fix for this will need to involve...will update the bug when we come across them!

### PR DESCRIPTION
**Pull request by gideonthomas**
This is a combination of https://github.com/mozilla/thimble.webmaker.org/pull/829 and https://github.com/mozilla/thimble.webmaker.org/pull/827

### CODE REVIEW

**Comment by gideonthomas** [comment]
#828 fix

**Comment by sedge** [comment]
This needs one more commit to be in a mostly working state: https://github.com/sedge/thimble.webmaker.org/commit/4c77961528636941c49850005555ad7ccc323469

Bugs I've noticed:

1. Pathing is still odd when a project opens. Sometimes styling doesn't appear in the live preview. Other times an error pops up saying that an `index.html` file is required for preview (despite it being in the tree)
2. Creating a new project sucks in `tutorial.css` and `tutorial-style-guide.html`. This is a regression, so something wonky has happened with the history.

**Comment by humphd** [comment]
The index.html not having CSS is my mission for tomorrow.  It's a bug in the timing of the live dev server loading and it using raw file system blob urls vs. rewritten instrumented pages.

**Comment by sedge** [comment]
The strange files popping up were artifacts in my indexeddb. Clearing it fixed that issue.

**Comment by humphd** [comment]
...and https://github.com/humphd/brackets/pull/419 should fix 1)

**Pull request merged**
