### PR TITLE
Styling fixes for Safari

### LINKED ISSUE #664: Bad styling in Safari on the editor settings popup.
From a usertesting video...

image

### LINKED ISSUE #1059: Safari - Garbage icon animation is missing on My Projects page
The top of the garbage can should open...

image

### LINKED ISSUE #1061: Safari - Hover effect on starter projects not present
When hovering over these...

image

...they should animate slightly and become faint.

### LINKED ISSUE #1062: Safari - Non-signed in Publish strobe effect is missing
When you click Publish and you're not signed in, the Log In and Sign Up words should have an animated white background effect, but they don't.

image

### PR DESCRIPTION
**Pull request by flukeout**
A bunch of fixes for Safari
* Fixes #664 - Fixes layout of editor settings popup 
* Fixes #1062 - Adds strobe effect when clicking Publish and not signed in
* Fixes #1059 - Adds garbage can animation on My Projects page
* Fixes #1061 - Added hover effect to starter projects
* Fixed the New Project button animation on the homepage

### CODE REVIEW

**Comment by gideonthomas** [comment]
Your fix for #664 seems to break in chrome though

**Comment by flukeout** [comment]
@gideonthomas This part of the committ changes the values to the new ones...

image

Looks like for some reason chrome was using the "left" old values. For me, restarting the thimble server fixed the problem. Can you try again with a server restart?

**Comment by gideonthomas** [comment]
Sure

**Comment by gideonthomas** [comment]
ah good ol' caching!
r+

**Pull request merged**
