### PR TITLE
Changed the remix button position for touch mode.

### PR DESCRIPTION
**Pull request by flukeout**
Moved the remix button to the bottom right for touch mode...

image

Changed position and method for dismissing the expanded popup...

image

### CODE REVIEW

**Comment by flukeout** [comment]
@gideonthomas R?

**Comment by gideonthomas** [comment]
ooo nice!

**Comment by flukeout** [comment]
@gideonthomas Is that an R+?

**Comment by flukeout** [comment]
Oh wait, I see the label now, thanks!

**Pull request merged**
