### PR TITLE
Fix documentation to match new db schema

### PR DESCRIPTION
**Pull request by errietta**
from https://github.com/mozilla/id.webmaker.org/issues/390#issuecomment-140748446

### CODE REVIEW

**Comment by sedge** [comment]
@errietta Can you confirm that this step is successful with the updated schema?

**Comment by sedge** [comment]
Also, workflow nit, can you rename the commit to reference issue #1116 ? It makes it way easier to track changes if we can jump straight to the issue from the commit history.

Something like: `Fixed #1116 - Fix documentation to ...`

**Comment by errietta** [comment]
@sedge confirmed working, also done :smile:

**Comment by sedge** [comment]
Thank you! r+ :+1:

**Pull request merged**
